---
#provisioning
common_packages:
  - vim-nox
  - openntpd
  - sudo
common_shell: /bin/bash
common_member_of: sudo
common_services:
  - sshd
  - openntpd
common_username: tester
common_password: "{{ lookup('file', 'files/hashed_password') }}"
common_local_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"